image: spittet/node-mongodb

pipelines:
  default:
    - step:
        script:
          - service mongod start # starts mongo
          - export MONGOHOST=localhost # bette way to make it?
          - npm install
          - npm test