version: "2"
services:

  mongo:
    image: mongo
    volumes:
      - ./data/mongo:/data/db

  npm_test:
    image: node
    links:
      - mongo
    volumes:
      - ./:/code
    working_dir: /code
    command: bash -c "npm install && npm test"